# Generated by Django 6.0 on 2025-12-23 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyanalysis',
            options={'ordering': ['-date', 'day'], 'verbose_name': 'Daily Analysis', 'verbose_name_plural': 'Daily Analysis'},
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='close_value',
            field=models.IntegerField(help_text='3-digit vertical value (e.g. 155)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='mid_value',
            field=models.IntegerField(help_text='2-digit center value (e.g. 51)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='open_value',
            field=models.IntegerField(help_text='3-digit vertical value (e.g. 799)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
